"""Reconstruct MIRCA.txt from the original MIRCA2000 .asc.gz rasters.

The MIRCA.txt file is a combined table of irrigated and rainfed harvested
areas (hectares) for each of the 26 MIRCA2000 crops at half-degree
resolution.  It is consumed by the remapping pipeline via
read_table_then2map() in lpjg_io.py.

Historically this file was generated by MATLAB preprocessing scripts
(mirca_combine_irr_rf.m / import_mirca.m).  This Python equivalent reads
the same 52 raw rasters from the ``originals/`` directory and produces a
byte-compatible replacement.

Usage:
    python -m landsymm.remapping.rebuild_mirca_txt          # default paths
    python -m landsymm.remapping.rebuild_mirca_txt --verify  # also validate vs cache
"""
from __future__ import annotations

import argparse
import gzip
import os
from pathlib import Path

import numpy as np

from landsymm.config import get_geodata_dir

MIRCA_CROPS = [
    "Wheat", "Maize", "Rice", "Barley", "Rye", "Millet",
    "Sorghum", "Soybeans", "Sunflower", "Potatoes", "Cassava",
    "Sugarcane", "Sugarbeet", "Oilpalm", "RapeseedCanola",
    "GroundnutsPeanuts", "Pulses", "Citrus", "Datepalm",
    "GrapesVine", "Cotton", "Cocoa", "Coffee",
    "OtherPerennials", "FodderGrasses", "OtherAnnuals",
]

NROWS = 360
NCOLS = 720
HEADER_LINES = 6
NODATA = -9999


def _read_asc_gz(path: str) -> np.ndarray:
    """Read a gzipped ESRI ASCII grid, replicating MATLAB import_mirca.m."""
    with gzip.open(path, "rt") as f:
        for _ in range(HEADER_LINES):
            f.readline()
        data = np.loadtxt(f)
    data = data[:, :NCOLS]
    data = np.flipud(data)
    data[data == NODATA] = np.nan
    if np.any(data < 0):
        print(f"  Warning: negative values in {os.path.basename(path)}")
    return data


def build_mirca_table(originals_dir: str) -> tuple[np.ndarray, list[str]]:
    """Read all 52 .asc.gz rasters and assemble the MIRCA table.

    Returns (table, col_names) where table has shape (n_cells, 54):
    columns are [Lon, Lat, Wheat_IR, Maize_IR, ..., OtherAnnuals_RF].
    """
    n_crops = len(MIRCA_CROPS)
    maps_ir = np.full((NROWS, NCOLS, n_crops), np.nan)
    maps_rf = np.full((NROWS, NCOLS, n_crops), np.nan)

    for c, crop_name in enumerate(MIRCA_CROPS):
        num = f"{c + 1:02d}"
        ir_path = os.path.join(originals_dir, f"annual_area_harvested_irc_crop{num}_ha_30mn.asc.gz")
        rf_path = os.path.join(originals_dir, f"annual_area_harvested_rfc_crop{num}_ha_30mn.asc.gz")
        print(f"  Reading crop {num}/{n_crops}: {crop_name}")
        maps_ir[:, :, c] = _read_asc_gz(ir_path)
        maps_rf[:, :, c] = _read_asc_gz(rf_path)

    maps_all = np.concatenate([maps_ir, maps_rf], axis=2)  # (360, 720, 52)
    col_names_ir = [f"{crop}_IR" for crop in MIRCA_CROPS]
    col_names_rf = [f"{crop}_RF" for crop in MIRCA_CROPS]
    col_names = col_names_ir + col_names_rf

    lons = np.arange(-179.75, 180, 0.5)
    lats = np.arange(-89.75, 90, 0.5)
    lon_grid, lat_grid = np.meshgrid(lons, lats)

    total_area = np.nansum(maps_all, axis=2)
    has_data = total_area > 0

    n_cells = int(np.sum(has_data))
    print(f"  Cells with crop data: {n_cells}")

    lon_flat = lon_grid[has_data]
    lat_flat = lat_grid[has_data]
    data_flat = maps_all[has_data, :]
    data_flat = np.nan_to_num(data_flat, nan=0.0)

    table = np.column_stack([lon_flat, lat_flat, data_flat])
    return table, col_names


def write_mirca_txt(table: np.ndarray, col_names: list[str], out_path: str) -> None:
    """Write the MIRCA table as a tab-delimited text file."""
    header = "Lon\tLat\t" + "\t".join(col_names)
    fmt = ["%.2f", "%.2f"] + ["%.6f"] * len(col_names)
    np.savetxt(out_path, table, header=header, comments="", delimiter="\t", fmt=fmt)
    size_mb = os.path.getsize(out_path) / 1e6
    print(f"  Written: {out_path} ({size_mb:.1f} MB, {table.shape[0]} cells)")


def verify_against_cache(table: np.ndarray, col_names: list[str], cache_path: str) -> bool:
    """Compare reconstructed data against the .maps.mat cache."""
    import h5py

    print(f"\n  Verifying against cache: {cache_path}")
    with h5py.File(cache_path, "r") as f:
        os_ = f["out_struct"]
        cached_maps = os_["maps_YXv"][:]  # (52, 720, 360) in HDF5 transposed order
        vn_refs = os_["varNames"][0]
        cached_names = []
        for ref in vn_refs:
            obj = f[ref]
            cached_names.append("".join(chr(c) for c in obj[:].flatten()))

    cached_maps = cached_maps.transpose(2, 1, 0)  # -> (360, 720, 52)

    if col_names != cached_names:
        print("  MISMATCH: column name ordering differs!")
        print(f"    Rebuilt:  {col_names[:5]}...")
        print(f"    Cached:   {cached_names[:5]}...")
        return False
    print("  Column names match.")

    lons = np.arange(-179.75, 180, 0.5)
    lats = np.arange(-89.75, 90, 0.5)
    rebuilt_maps = np.full((NROWS, NCOLS, 52), np.nan)
    for i in range(table.shape[0]):
        lon_i, lat_i = table[i, 0], table[i, 1]
        xi = int(round((lon_i + 179.75) / 0.5))
        yi = int(round((lat_i + 89.75) / 0.5))
        rebuilt_maps[yi, xi, :] = table[i, 2:]

    cached_maps_clean = cached_maps.copy()
    cached_maps_clean[np.isnan(cached_maps_clean)] = 0.0
    rebuilt_maps_clean = rebuilt_maps.copy()
    rebuilt_maps_clean[np.isnan(rebuilt_maps_clean)] = 0.0

    max_diff = np.max(np.abs(rebuilt_maps_clean - cached_maps_clean))
    mean_diff = np.mean(np.abs(rebuilt_maps_clean - cached_maps_clean))
    n_nonzero_cache = np.sum(cached_maps_clean > 0)
    n_nonzero_rebuilt = np.sum(rebuilt_maps_clean > 0)

    print(f"  Max absolute difference: {max_diff:.10f}")
    print(f"  Mean absolute difference: {mean_diff:.10e}")
    print(f"  Non-zero cells in cache: {n_nonzero_cache}")
    print(f"  Non-zero cells in rebuilt: {n_nonzero_rebuilt}")

    if max_diff < 1e-3:
        print("  PASS: Reconstruction matches cache within tolerance.")
        return True
    else:
        print("  FAIL: Reconstruction differs from cache beyond tolerance.")
        where_diff = np.abs(rebuilt_maps_clean - cached_maps_clean) > 1e-3
        print(f"  Cells exceeding tolerance: {np.sum(where_diff)}")
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Reconstruct MIRCA.txt from raw .asc.gz rasters.")
    parser.add_argument("--verify", action="store_true", help="Validate against .maps.mat cache")
    parser.add_argument("--originals-dir", default=None, help="Path to originals/ directory")
    parser.add_argument("--output", default=None, help="Output path for MIRCA.txt")
    args = parser.parse_args()

    geodata = get_geodata_dir()
    mirca_base = geodata / "MIRCA" / "harvested_area_grids_26crops_30mn"
    originals_dir = args.originals_dir or str(mirca_base / "originals")
    out_path = args.output or str(mirca_base / "MIRCA.txt")
    cache_path = str(mirca_base / "MIRCA.txt.maps.mat")

    print("Rebuilding MIRCA.txt from raw rasters...")
    print(f"  Source: {originals_dir}")
    print(f"  Output: {out_path}")

    table, col_names = build_mirca_table(originals_dir)
    write_mirca_txt(table, col_names, out_path)

    if args.verify:
        if os.path.exists(cache_path):
            verify_against_cache(table, col_names, cache_path)
        else:
            print(f"  Cache not found at {cache_path}, skipping verification.")

    print("\nDone.")


if __name__ == "__main__":
    main()
